services:
  postgres:
    image: ${POSTGRES_IMAGE:-postgres:1.7.11}
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-dbagent}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      POSTGRES_DB: ${POSTGRES_DB:-dbagent}
      POSTGRES_INITDB_ARGS: '--data-checksums'
      POSTGRES_SHARED_PRELOAD_LIBRARIES: 'pg_stat_statements'
    command:
      - 'postgres'
      - '-c'
      - 'shared_preload_libraries=pg_stat_statements'
      - '-c'
      - 'pg_stat_statements.track=all'
      - '-c'
      - 'pg_stat_statements.max=10000'
    ports:
      - '5432:5432'
    volumes:
      - agent_postgres_data:/var/lib/postgresql/data
      - ./apps/dbagent/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql

  xata-agent:
    image: ${AGENT_IMAGE:-dbagent}
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-dbagent}:${POSTGRES_PASSWORD:-changeme}@postgres:5432/${POSTGRES_DB:-dbagent}
      NODE_ENV: production
      AUTH_TRUST_HOST: ${AUTH_TRUST_HOST:-localhost}
    env_file: '.env.production'
    ports:
      - '8080:8080'
    depends_on:
      - postgres

volumes:
  agent_postgres_data:
